version: '3.5'

services:

  web_server:
    container_name: web_server
    build:
      context: .
      dockerfile: ./docker/web_server/Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/lib/supercontest/certbot/conf:/etc/letsencrypt
      - /var/lib/supercontest/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      - app_prod

  app_prod:
    container_name: app_prod
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - .:/sc
    expose:
      - 8080
    command: "uwsgi --ini ./docker/app/uwsgi.ini --socket :8080"
    depends_on:
      - database

  app_dev:
    container_name: app_dev
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - .:/sc
    ports:
      - 5000:5000
    command: "uwsgi --ini ./docker/app/uwsgi.ini --socket 0.0.0.0:5000 --protocol http --py-autoreload 1"
    depends_on:
      - database

  database:
    container_name: database
    image: postgres
    env_file:
      - ./docker/database/private.conf
      - ./docker/database/public.conf
    ports:
      - 5432:5432
    volumes:
      - db_volume:/var/lib/postgresql/data

  certbot:
    container_name: certbot
    image: certbot/certbot
    volumes:
      - /var/lib/supercontest/certbot/conf:/etc/letsencrypt
      - /var/lib/supercontest/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  db_volume:
