version: '3'

services:

  supercontest-app-prod:
    container_name: supercontest-app-prod
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - .:/sc
    expose:
      - 8080
    environment:
      - VIRTUAL_HOST=southbaysupercontest.com,www.southbaysupercontest.com
      - VIRTUAL_PROTO=uwsgi
      - LETSENCRYPT_HOST=southbaysupercontest.com
      - LETSENCRYPT_EMAIL=brian.mahlstedt@gmail.com
    command: "uwsgi --ini ./docker/app/uwsgi.ini:prod"
    depends_on:
      - supercontest-database

  supercontest-app-dev:
    container_name: supercontest-app-dev
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - .:/sc
    ports:
      - 5000:5000
    environment:
      - SC_DEV=1
    command: "uwsgi --ini ./docker/app/uwsgi.ini:dev"
    depends_on:
      - supercontest-database

  supercontest-database:
    container_name: supercontest-database
    image: postgres
    env_file:
      - ./docker/database/private.conf
      - ./docker/database/public.conf
    ports:
      - 5432:5432
    volumes:
      - db_volume:/var/lib/postgresql/data

volumes:
  db_volume:

networks:
  default:
    external:
      name: nginx-proxy
