version: '3.5'

services:

  web_server:
    container_name: nginx
    build:
      context: .
      dockerfile: ./docker/web_server/Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      - app

  app:
    container_name: flask
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - .:/sc
    expose:
      - 8080
    depends_on:
      - database

  database:
    container_name: postgres
    build:
      context: .
      dockerfile: ./docker/database/Dockerfile
    env_file: ./docker/database/private.conf
    ports:
      - 5432:5432
    volumes:
      - db_volume:/var/lib/postgresql/data

  certbot:
    container_name: certbot
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  db_volume:
