"""removed points from picks table and user backref (still kept fk)

Revision ID: 1f900fb39cc3
Revises: 1defe51620ac
Create Date: 2019-03-15 13:37:10.485804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f900fb39cc3'
down_revision = '1defe51620ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pick', schema=None) as batch_op:
        batch_op.drop_column('points')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pick', schema=None) as batch_op:
        batch_op.add_column(sa.Column('points', sa.FLOAT(), nullable=True))

    # ### end Alembic commands ###
