"""adding server defaults for new cols

Revision ID: 43f165b0258d
Revises: 783195f02f00
Create Date: 2018-11-03 16:22:51.562895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43f165b0258d'
down_revision = '783195f02f00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(length=225, collation='NOCASE'), server_default='', nullable=False))
    op.add_column('user', sa.Column('email_confirmed_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False))
    op.add_column('user', sa.Column('password', sa.String(length=255), server_default='', nullable=False))
    op.add_column('user', sa.Column('username', sa.String(length=100, collation='NOCASE'), server_default='', nullable=False))
    op.create_unique_constraint(None, 'user', ['email'])
    op.create_unique_constraint(None, 'user', ['username'])
    op.drop_column('user', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.VARCHAR(), nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'username')
    op.drop_column('user', 'password')
    op.drop_column('user', 'is_active')
    op.drop_column('user', 'email_confirmed_at')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
