"""migrated from sqlite to postgres, no changes to models

Revision ID: 46a3c7d90935
Revises: df7ccd78fba6
Create Date: 2019-04-05 13:34:09.983556

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '46a3c7d90935'
down_revision = 'df7ccd78fba6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matchup', schema=None) as batch_op:
        batch_op.alter_column('datetime',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('favored_team',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('line',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('underdog_team',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('week',
               existing_type=sa.BIGINT(),
               nullable=False)

    with op.batch_alter_table('pick', schema=None) as batch_op:
        batch_op.alter_column('team',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('week',
               existing_type=sa.BIGINT(),
               nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text(u"''::text"))
        batch_op.alter_column('first_name',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text(u"''::text"))
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text(u'true'))
        batch_op.alter_column('last_name',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text(u"''::text"))
        batch_op.alter_column('password',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text(u"''::text"))
        batch_op.create_unique_constraint('email_constraint', ['email'])
        batch_op.drop_index('idx_16448_sqlite_autoindex_user_1')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('idx_16448_sqlite_autoindex_user_1', ['email'], unique=True)
        batch_op.drop_constraint('email_constraint', type_='unique')
        batch_op.alter_column('password',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text(u"''::text"))
        batch_op.alter_column('last_name',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text(u"''::text"))
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text(u'true'))
        batch_op.alter_column('first_name',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text(u"''::text"))
        batch_op.alter_column('email',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text(u"''::text"))

    with op.batch_alter_table('pick', schema=None) as batch_op:
        batch_op.alter_column('week',
               existing_type=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('team',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('matchup', schema=None) as batch_op:
        batch_op.alter_column('week',
               existing_type=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('underdog_team',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('line',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('favored_team',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('datetime',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###
