"""adding season

Revision ID: 5611e69e53d2
Revises: 493b07f8aea0
Create Date: 2019-08-31 23:00:09.299431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5611e69e53d2'
down_revision = '493b07f8aea0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matchup', sa.Column('season', sa.Integer()))
    op.execute('UPDATE matchup SET season = 2018')
    op.alter_column('matchup', 'season', nullable=False)

    op.add_column('pick', sa.Column('season', sa.Integer()))
    op.execute('UPDATE pick SET season = 2018')
    op.alter_column('pick', 'season', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pick', schema=None) as batch_op:
        batch_op.drop_column('season')

    with op.batch_alter_table('matchup', schema=None) as batch_op:
        batch_op.drop_column('season')

    # ### end Alembic commands ###
