"""changing to explicit constraints

Revision ID: 894dba7ef5ad
Revises: 43f165b0258d
Create Date: 2018-11-03 16:33:50.817769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '894dba7ef5ad'
down_revision = '43f165b0258d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('email_constraint', ['email'])
        batch_op.create_unique_constraint('password_constraint', ['password'])
        batch_op.create_unique_constraint('username_constraint', ['username'])
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(), nullable=False))
        batch_op.drop_constraint('username_constraint', type_='unique')
        batch_op.drop_constraint('password_constraint', type_='unique')
        batch_op.drop_constraint('email_constraint', type_='unique')

    # ### end Alembic commands ###
