"""adding winner to matchup table and points to pick table

Revision ID: df7ccd78fba6
Revises: 1f900fb39cc3
Create Date: 2019-03-18 22:58:08.870740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df7ccd78fba6'
down_revision = '1f900fb39cc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matchup', schema=None) as batch_op:
        batch_op.add_column(sa.Column('winner', sa.String(), nullable=True))

    with op.batch_alter_table('pick', schema=None) as batch_op:
        batch_op.add_column(sa.Column('points', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pick', schema=None) as batch_op:
        batch_op.drop_column('points')

    with op.batch_alter_table('matchup', schema=None) as batch_op:
        batch_op.drop_column('winner')

    # ### end Alembic commands ###
